# Generated by Django 3.1.5 on 2021-02-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
