# Generated by Django 3.1.5 on 2021-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_requestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'Confirmed'), (3, 'Reject'), (4, 'Sent via mail Service'), (5, 'received Book'), (6, 'Sent Back'), (7, 'Received Back (Final)')]),
        ),
    ]
