# Generated by Django 3.1.5 on 2021-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210307_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=True, null=True, upload_to=''),
        ),
    ]
