"""Added required tables

Revision ID: c358b3b57073
Revises: ddbbb5334900
Create Date: 2021-04-15 18:31:39.907841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c358b3b57073'
down_revision = 'ddbbb5334900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
