"""Added required tables

Revision ID: ddbbb5334900
Revises: 
Create Date: 2021-04-15 18:16:09.286570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbbb5334900'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_ts', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoom_events')
    # ### end Alembic commands ###
