version: "3.8"

services:
  memcached:
    ports:
      - "11211:11211"

  db:
    ports:
      - "5432:5432"

  broker:
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "8000:8000"
    environment:
      - ENV=dev

  worker:
    build: .
