version: "3.8"

x-defaults: &x-defaults
  env_file:
    - .env
  depends_on:
    - db
    - broker
    - memcached
  image: local:0.0.1
  restart: always
  build: .


services:
  memcached:
    image: memcached:latest
    container_name: "memcached"

  db:
    image: postgres:12.3-alpine
    restart: always
    container_name: "db"
    env_file:
      - .env
#    environment:
#      - POSTGRES_USER=mailler
#      - POSTGRES_DB=mailler
#      - POSTGRES_PASSWORD=few6FGweu4762qa345g5efsaOPqdwr
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    image: nginx:1.19
    container_name: "web"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  broker:
    image: rabbitmq:3-management
    container_name: "broker"
    env_file:
      - .env

  backend:
    container_name: "backend"
    <<: *x-defaults

  worker:
    container_name: "worker"
    environment:
      - MODE=worker
    <<: *x-defaults

  # TODO: add celerybeat

volumes:
  db_data: {}
