version: "3.8"

services:
  backend:
    container_name: "backend"
    image: local:0.0.1
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./:/project"

  db:
    image: postgres:12.3-alpine
    restart: always
    container_name: "db"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
    depends_on:
      - db
    links:
      - db

volumes:
  db_data: {}
